/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TitleStyle } from "./components/chat-modal/types";
export { TitleStyle } from "./components/chat-modal/types";
export namespace Components {
    interface ChatModal {
        /**
          * @default Env.API_URL
         */
        "apiEndpoint": string;
        /**
          * @default 16
         */
        "iconSize": number;
        /**
          * @default "Que puis-je faire pour vous ?"
         */
        "modalTitle": string;
        /**
          * @default {}
         */
        "titleStyle": Partial<TitleStyle>;
    }
    interface ChatSkeleton {
    }
    interface ChatWidget {
        /**
          * @default Env.API_URL
         */
        "apiEndpoint": string;
    }
    interface SatisfactionButtons {
    }
}
declare global {
    interface HTMLChatModalElement extends Components.ChatModal, HTMLStencilElement {
    }
    var HTMLChatModalElement: {
        prototype: HTMLChatModalElement;
        new (): HTMLChatModalElement;
    };
    interface HTMLChatSkeletonElement extends Components.ChatSkeleton, HTMLStencilElement {
    }
    var HTMLChatSkeletonElement: {
        prototype: HTMLChatSkeletonElement;
        new (): HTMLChatSkeletonElement;
    };
    interface HTMLChatWidgetElement extends Components.ChatWidget, HTMLStencilElement {
    }
    var HTMLChatWidgetElement: {
        prototype: HTMLChatWidgetElement;
        new (): HTMLChatWidgetElement;
    };
    interface HTMLSatisfactionButtonsElement extends Components.SatisfactionButtons, HTMLStencilElement {
    }
    var HTMLSatisfactionButtonsElement: {
        prototype: HTMLSatisfactionButtonsElement;
        new (): HTMLSatisfactionButtonsElement;
    };
    interface HTMLElementTagNameMap {
        "chat-modal": HTMLChatModalElement;
        "chat-skeleton": HTMLChatSkeletonElement;
        "chat-widget": HTMLChatWidgetElement;
        "satisfaction-buttons": HTMLSatisfactionButtonsElement;
    }
}
declare namespace LocalJSX {
    interface ChatModal {
        /**
          * @default Env.API_URL
         */
        "apiEndpoint"?: string;
        /**
          * @default 16
         */
        "iconSize"?: number;
        /**
          * @default "Que puis-je faire pour vous ?"
         */
        "modalTitle"?: string;
        /**
          * @default {}
         */
        "titleStyle"?: Partial<TitleStyle>;
    }
    interface ChatSkeleton {
    }
    interface ChatWidget {
        /**
          * @default Env.API_URL
         */
        "apiEndpoint"?: string;
    }
    interface SatisfactionButtons {
    }
    interface IntrinsicElements {
        "chat-modal": ChatModal;
        "chat-skeleton": ChatSkeleton;
        "chat-widget": ChatWidget;
        "satisfaction-buttons": SatisfactionButtons;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chat-modal": LocalJSX.ChatModal & JSXBase.HTMLAttributes<HTMLChatModalElement>;
            "chat-skeleton": LocalJSX.ChatSkeleton & JSXBase.HTMLAttributes<HTMLChatSkeletonElement>;
            "chat-widget": LocalJSX.ChatWidget & JSXBase.HTMLAttributes<HTMLChatWidgetElement>;
            "satisfaction-buttons": LocalJSX.SatisfactionButtons & JSXBase.HTMLAttributes<HTMLSatisfactionButtonsElement>;
        }
    }
}
